version: '3'
services:
  api-by-pass-cloudflare:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - flaresolverr
      - postgres_db
    networks:
      - api-by-pass-cloudflare

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - api-by-pass-cloudflare

  postgres_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    restart: unless-stopped
    networks:
      - api-by-pass-cloudflare

networks:
  api-by-pass-cloudflare:
  